### PR TITLE
Minimal support for PVR API 3.0.0

### PR DESCRIPTION
**Pull request by metaron-uk**
Add-on part of https://github.com/xbmc/xbmc/pull/7626
The mythtv client wasn't actually using most of the features affected by API 3.0.0, so the list of changes is minimal. They actually remove some 'command failed' error cases.
See commit messages for details of things assessed/addressed.

@janbar - let me know if you want a similar 'minimal' PR for your doityourself branch.
I'll hold any 'full feature' PRs until the merge is done - I suspect they won't be as trivial...

Other Pings: @ksooo @ryangribble

### CODE REVIEW

**Comment by janbar** [comment]
@metaron-uk, thanks. If you have little time, i would like you make a PR on this repos but based on my branch 3.2.1. Which was ready to be pulled. Then i pull the 3.2.1 and your new PR will be valid to be pulled on 3.2.1. Let me know, thanks

**Comment by metaron-uk** [comment]
@janbar I've pushed a 3.2.1 based version (https://github.com/metaron-uk/pvr.mythtv/commits/321API3). Mention me when 321 is merged and I'll force push this here to replace the current one.

Edit: I was able to cherry-pick the main part of the change directly onto your 3.2.1 branch, so if this does get merged before 3.2.1 it shouldn't cause you too much trouble.

**Comment by janbar** [comment]
@metaron-uk the 3.2.1 is merged now, since PR #27. Then it would be more easy to merge API change to all existing development branches, avoiding merge with conflicts.

**Comment by janbar** [comment]
Your branch 321API3 is ok. Thanks :+1:

**Comment by metaron-uk** [comment]
@janbar forced pushed to this PR from 321API3 branch.

**Pull request merged**
