### PR TITLE
4.10.0

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by metaron-uk** [comment]
Jean-Luc,
Unfortunately since this pull request was merged (specifically commit https://github.com/janbar/pvr.mythtv/commit/8b1a1b952318a8aac0bc5809ffdcc9d5caaf66d0) I don't get my full list of recordings anymore:
Before:
screenshot060
After:
screenshot059
Andrew

EDIT also posted on the forum: http://forum.kodi.tv/showthread.php?tid=198833&pid=2480733#pid2480733

**Comment by janbar** [comment]
Hi Andrew,

Have you the issue all the times ?
I mean, if you restart kodi, is the issue is yet ?

**Comment by metaron-uk** [comment]
Yes. Would a debug log help?
If you want me to try a special build let me know.
Andrew

**Comment by janbar** [comment]
Okay nice ! I had this issue a short time and then no more. I give you a stuff to test ...

**Comment by janbar** [comment]
https://github.com/kodi-pvr/pvr.mythtv/blob/master/lib/cppmyth/src/private/wsrequest.cpp#L61
https://github.com/kodi-pvr/pvr.mythtv/blob/master/lib/cppmyth/src/private/wsrequest.cpp#L76
can you try with value false for RequestAcceptEncoding ?

**Comment by janbar** [comment]
The addon use only the call of WSRequest::WSRequest(const std::string& server, unsigned port). So updating line 61 should be enougth to try.

**Comment by metaron-uk** [comment]
With both the changes you suggested it works:
screenshot061

I'm using a 0.27.6 based backend

**Comment by janbar** [comment]
Okay, seems it is an issue from the backend. But I have it also with 0.28.

**Comment by janbar** [comment]
In fact with cppmyth 2.8 , I added the support of content encoding for http request. It reduces greatly the size of network transfer by encoding content of request with gzip.

**Comment by janbar** [comment]
But seems backend send only 100 rows !

**Comment by janbar** [comment]
Could you tell me how many recordings was retrieved wirth the issue ?

**Comment by janbar** [comment]
That's really strange. With 0.29 , I haven't the issue.

**Comment by janbar** [comment]
mmm, 100 or 200 etc : that 's normal because the content is downloaded by 101 rows and seems a block is broken and then the loading is aborted.

**Comment by metaron-uk** [comment]
(version < 88 ? false : true)?

With set to 'false' : http://sprunge.us/CAJG
With set to 'true' : http://sprunge.us/WMQc

I have a _lot_ of recordings...

**Comment by janbar** [comment]
Thanks Andrew. I have stuff to investigate with your logs. I will let you know when I fix the issue.
If I found a bug from the backend , I will disable the encoding. I have some time now to fix it.

**Comment by metaron-uk** [comment]
good luck!

**Comment by janbar** [comment]
```
16:22:19.342 T:2634373952   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)Document: failed to parse: 1: unexpected end of input
16:22:19.342 T:2634373952   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)GetRecordedList1_5: unexpected content
16:22:19.345 T:2634373952   DEBUG: AddOnLog: MythTV PVR Client: FillRecordings: count 700
```

**Comment by janbar** [comment]
I merged the workaround in 4.12.3, for the time I investigate the issue.

**Comment by metaron-uk** [comment]
Thanks.

**Comment by janbar** [comment]
I pushed a fix. Please could try the version 4.12.4 and let me know. Thanks

**Comment by metaron-uk** [comment]
Works :+1: 
your 'devel' branch works with Lxxx against 0.27.6 as well.
Thanks Jean-Luc.

**Comment by janbar** [comment]
Good. Thanks to you.

**Pull request merged**
