### PR TITLE
5.0.8

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@janbar how about we just make repo the upstream and deprecate this one?
Only thing you have to do is create github release tags and send a bump request to here
https://github.com/xbmc/repo-binary-addons  (master and Krypton branch).

That saves you all this work.

**Comment by janbar** [comment]
Ah YES. Thanks @MartijnKaijser

**Comment by janbar** [comment]
@MartijnKaijser , about transifex, where translations will be pushed ?

**Comment by MartijnKaijser** [comment]
@janbar you'll need to give permission to our transifex robot so it can push to your repo. I'll ping @alanwww1 to get location changed.
edit:
You can already change repo now if you want.

**Comment by janbar** [comment]
Okay thanks. I change it now.

**Pull request closed without merging**
